#include "protheus.ch"
#include "RestFul.CH"
#include "topconn.ch"
#include "tbiconn.ch"

WSRESTFUL Login Description "Login"
    WSMETHOD POST Description "Valida os dados de login no portal" WSSYNTAX "/login"
End WSRESTFUL

WSMETHOD POST WSRESTFUL Login
    Local cContent := Self:GetContent()
    Local aResponse := LoginService():Login(cContent)

    ::SetStatus(aResponse["status"])
    ::SetResponse(aResponse["message"])
Return
